repos:
  # ============================
  # 1. Ruff — линтер + автофикс
  # ============================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]  # Автоматически исправляет ошибки, если возможно

  # ============================
  # 2. Black — автоформатирование кода
  # ============================
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  # ============================
  # 3. Mypy — статическая проверка типов. Временно отключена для экономии времени
  # ============================
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.17.1
#    hooks:
#      - id: mypy
#        args: ["--strict"]
#        additional_dependencies: ["sqlalchemy", "pydantic"]

  # ============================
  # 4. Проверка на секреты в коде
  # ============================
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  # ============================
  # 5. Базовые проверки pre-commit-hooks
  # ============================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace            # Убирает лишние пробелы
      - id: end-of-file-fixer             # Следит, чтобы был ровно один перевод строки в конце
      - id: check-yaml                    # Проверка корректности YAML
      - id: check-added-large-files       # Блокирует коммит больших файлов (>5MB)
      - id: check-merge-conflict          # Проверка на неразрешённые конфликты мерджа
      - id: check-ast                     # Проверка, что Python-файлы парсятся корректно
