version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    labels:
      logging: promtail
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    env_file:
      - .env
    labels:
      logging: promtail
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "bash init_migrations.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  loki:
    image: grafana/loki:2.9.8
    command: [ "-config.file=/etc/loki/loki-config.yaml" ]
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.8
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
      - web

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml:ro
      - prometheus_data:/prometheus
    env_file:
      - .env

  grafana:
    image: grafana/grafana:11.1.0
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources/loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml:ro
      - ./grafana/provisioning/datasources/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml:ro
    ports:
      - "3000:3000"
    depends_on:
      - loki
    env_file:
      - .env

volumes:
  db_data:
  loki_data:
  prometheus_data:
  grafana_data:
