[pytest]
# Каталог, где pytest ищет тесты
testpaths = tests

# Шаблон имен тестов
python_files = test_*.py *_test.py

# Шаблон имен классов и функций
python_classes = Test*
python_functions = test_*

# Включаем более подробный вывод
addopts = -ra -q --tb=short

# Плагин для поддержки асинхронных тестов
asyncio_mode = auto
