# Версия Python, под которую настраиваем Ruff
target-version = "py312"

# Максимальная длина строки
line-length = 88

# Автоматическое исправление ошибок
fix = true

# Секция линтера
[lint]
# Включаем набор правил
select = [
    "E",      # PEP8 ошибки
    "F",      # Ошибки синтаксиса
    "B",      # Ошибки из bugbear
    "I",      # Сортировка импортов
    "N",      # PEP8-именование
    "UP",     # Советы по апгрейду кода
    "ASYNC",  # Проверка async/await
]

# Игнорируем определённые проверки
ignore = [
    "F401",  # Неиспользуемый импорт (часто нужно в __init__.py)
    "E501",  # Длина строки (отдаём на откуп Black)
    "B008"
]

# Исключаем папки и файлы из проверок
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    "migrations",
    "tests/__pycache__",
]
